### ISSUE TITLE
bug cuando no hay "jshintConfig" en "best-promise"

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#29]
Corro con la versión actual de best-promise [213cd6c3204a047e5d87448ebd439c76855f09e1](https://github.com/emilioplatzer/best-promise/commit/213cd6c3204a047e5d87448ebd439c76855f09e1) da el bug que muestro abajo:

```sh
c:\Hecho\npm\best-promise>qa-control .  --verbose

Starting qa-control on '.'...
Loaded default configuration.
Reading project directory...
Skipping directory '.git'.
Reading '.gitignore'...
Reading '.jshintrc'...
Reading '.npmignore'...
Reading '.travis.yml'...
Reading 'LEEME.md'...
Reading 'LICENSE'...
Reading 'Makefile'...
Reading 'README.md'...
Reading 'any-promise-shim.js'...
Reading 'any-promise.js'...
Reading 'best-promise.js'...
Skipping directory 'node_modules'.
Reading 'package.json'...
Skipping directory 'test'.
Controlling project information...
Checking rule 'exist_package_json'...
Checking rule 'qa_control_section_in_package_json'...
Checking rule 'package_version_in_qa_control_section'...
Checking rule 'invalid_qa_control_version'...
Checking rule 'deprecated_control_version'...
Checking rule 'repository_name_format'...

ERROR: undefined is not a function
STACK: TypeError: undefined is not a function
    at Object.qaControl.projectDefinition.0.0.1.rules.repository_name_format.checks.warnings (c:\hecho\npm\qa-control\bin\qa-control.js:281:58)
    at c:\hecho\npm\qa-control\bin\qa-control.js:658:34
    at tryCallOne (c:\hecho\npm\qa-control\node_modules\best-promise\node_modules\promise\lib\core.js:37:12)
    at c:\hecho\npm\qa-control\node_modules\best-promise\node_modules\promise\lib\core.js:103:15
    at flush (c:\hecho\npm\qa-control\node_modules\best-promise\node_modules\promise\node_modules\asap\raw.js:50:29)
    at process._tickCallback (node.js:355:11)
```

**Comment by diegoefe** [comment]
Con la versión actual de qa-control (https://github.com/codenautas/qa-control/commit/c8900c3adee90ca4a6144571d3fef771e6ef3251) no está pasando, verificalo por favor

**Comment by emilioplatzer** [comment]
Se debe haber arreglado. Si vuelve a aparecer lo reabrimos.
